# Copyright 2018 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ARG_FROM

MAINTAINER Zihong Zheng <zihongz@google.com>

RUN apt-get -y update

# Necessary to install iproute2
# https://github.com/GoogleCloudPlatform/netd/issues/125
RUN apt-mark unhold libcap2

RUN apt-get -y install curl jq bash iproute2
ADD scripts/install-cni.sh /install-cni.sh
ADD bin/ARG_ARCH/ARG_BIN /ARG_BIN

ENTRYPOINT ["/ARG_BIN"]
