# Copyright 2016 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## The curl, jq and toybox containers build the corresponding binaries.

FROM alpine:3.16 AS curl

ADD curl.tar.gz /

COPY third_party/static-curl/mykey.asc /mykey.asc
COPY third_party/static-curl/build.sh /build.sh

RUN /build.sh


FROM alpine:3.16 AS jq

ADD jq.tar.gz /

COPY build-jq.sh /build-jq.sh

RUN /build-jq.sh


FROM alpine:3.16 AS toybox

ADD toybox.tar.gz /

COPY build-toybox.sh /build-toybox.sh

RUN /build-toybox.sh


## The extras container extracts licenses and package data from Alpine packages.

FROM alpine:3.16 AS extras

ADD spdx-license.tar.gz /

COPY alpine-extractor.sh /alpine-extractor.sh

# All dependencies used in build scripts above should be listed.
RUN /alpine-extractor.sh musl openssl-dev openssl-libs-static linux-headers


## The bash container fetches bash-static (to be used as bash) from Debian repo.

FROM debian:11.4 AS bash

RUN apt-get update
RUN apt-get install -y --no-install-recommends --no-install-suggests bash-static
RUN dpkg -s bash-static > /tmp/status_bash-static


## This intermediate container pulls all pieces together from containers above.

FROM {ARG_FROM} AS intermediate

COPY --from=curl /tmp/release/curl /usr/bin/curl
COPY status.d/curl /var/lib/dpkg/status.d/curl

COPY --from=jq /tmp/release/jq /usr/bin/jq
COPY status.d/jq /var/lib/dpkg/status.d/jq

# Both toybox binary and symlinks
COPY --from=toybox /tmp/release/ /bin/
COPY status.d/toybox /var/lib/dpkg/status.d/toybox

# Licenses and package info
COPY --from=extras /tmp/extras/ /

COPY --from=bash /bin/bash-static /bin/bash
COPY --from=bash /tmp/status_bash-static /var/lib/dpkg/status.d/bash-static


## Run shell-test.sh in a standalone container. The outcome is discarded.

FROM intermediate AS test

COPY shell-test.sh /shell-test.sh

RUN /shell-test.sh


## Continue from the intermediate container (before running shell-test.sh) and complete the final image.

FROM intermediate

MAINTAINER Jingyuan Liang <jingyuanliang@google.com>

# This file is not being used. Include it to trigger the test run and allow manual testing.
COPY --from=test /shell-test.sh /shell-test.sh

# Add the platform-specific binary.
COPY bin/{ARG_OS}_{ARG_ARCH}/{ARG_BIN} /{ARG_BIN}

# Add third-party licenses.
COPY .licenses/ /LICENSES/
COPY --from=bash /usr/share/doc/bash-static/copyright /LICENSES/copyright.bash-static

ENV HOME /

ENTRYPOINT ["/{ARG_BIN}"]
