# Copyright 2016 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM alpine:3.16 AS curl

ADD curl.tar.gz /

COPY third_party/static-curl/mykey.asc /mykey.asc
COPY third_party/static-curl/build.sh /build.sh

RUN /build.sh


FROM alpine:3.16 AS jq

ADD jq.tar.gz /

COPY build-jq.sh /build-jq.sh

RUN /build-jq.sh


FROM debian:11.4 AS bash

RUN apt-get update
RUN apt-get install -y --no-install-recommends --no-install-suggests bash-static
RUN dpkg -s bash-static > /tmp/status_bash-static


FROM {ARG_FROM} AS intermediate

COPY --from=curl /tmp/release/curl /usr/bin/curl
COPY --from=curl /tmp/lib /lib
COPY status.d/curl /var/lib/dpkg/status.d/curl

COPY --from=jq /tmp/release/jq /usr/bin/jq
# jq doesn't have any dependency other than libc, which was covered by curl
COPY status.d/jq /var/lib/dpkg/status.d/jq

COPY --from=bash /bin/bash-static /bin/bash
COPY --from=bash /tmp/status_bash-static /var/lib/dpkg/status.d/bash-static

COPY toybox-{ARG_ARCH}.bin /bin/toybox
COPY status.d/toybox /var/lib/dpkg/status.d/toybox

COPY install-toybox.sh /install-toybox.sh

RUN /install-toybox.sh


FROM intermediate AS test

COPY shell-test.sh /shell-test.sh

RUN /shell-test.sh


FROM scratch

MAINTAINER Jingyuan Liang <jingyuanliang@google.com>

COPY --from=intermediate / /

# This file is not being used. Include it to trigger the test run and allow manual testing.
COPY --from=test /shell-test.sh /shell-test.sh

# Add the platform-specific binary.
COPY bin/{ARG_OS}_{ARG_ARCH}/{ARG_BIN} /{ARG_BIN}

# Add third-party licenses.
COPY .licenses/ /LICENSES/
COPY --from=bash /usr/share/doc/bash-static/copyright /LICENSES/copyright.bash-static

ENV HOME /

ENTRYPOINT ["/{ARG_BIN}"]
