name: Run lint

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Lint
      run: make -f Makefile.all lint
